{"cells":[{"cell_type":"code","execution_count":3,"id":"f5149aa6","metadata":{"colab":{"base_uri":"https://localhost:8080/","height":385},"executionInfo":{"elapsed":1144,"status":"error","timestamp":1727265705607,"user":{"displayName":"陳昇華","userId":"07161907235039823723"},"user_tz":-480},"id":"f5149aa6","outputId":"e128aa99-9ba9-4806-902f-7928943f0a3d"},"outputs":[{"name":"stderr","output_type":"stream","text":["\n","A module that was compiled using NumPy 1.x cannot be run in\n","NumPy 2.1.2 as it may crash. To support both 1.x and 2.x\n","versions of NumPy, modules must be compiled with NumPy 2.0.\n","Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n","\n","If you are a user of the module, the easiest solution will be to\n","downgrade to 'numpy<2' or try to upgrade the affected module.\n","We expect that some modules will need time to support NumPy 2.\n","\n","Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n","  File \"<frozen runpy>\", line 88, in _run_code\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n","    app.launch_new_instance()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1077, in launch_instance\n","    app.start()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n","    self.io_loop.start()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n","    self.asyncio_loop.run_forever()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 608, in run_forever\n","    self._run_once()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 1936, in _run_once\n","    handle._run()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\events.py\", line 84, in _run\n","    self._context.run(self._callback, *self._args)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n","    await self.process_one()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n","    await dispatch(*args)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n","    await result\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n","    await super().execute_request(stream, ident, parent)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n","    reply_content = await reply_content\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n","    res = shell.run_cell(\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n","    return super().run_cell(*args, **kwargs)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n","    result = self._run_cell(\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n","    result = runner(coro)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n","    if await self.run_code(code, result, async_=asy):\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_29968\\1473449029.py\", line 2, in <module>\n","    import pandas as pd\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py\", line 39, in <module>\n","    from pandas.compat import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n","    from pandas.compat.pyarrow import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n","    import pyarrow as pa\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n","    import pyarrow.lib as _lib\n"]},{"ename":"AttributeError","evalue":"_ARRAY_API not found","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)","\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"]},{"name":"stderr","output_type":"stream","text":["\n","A module that was compiled using NumPy 1.x cannot be run in\n","NumPy 2.1.2 as it may crash. To support both 1.x and 2.x\n","versions of NumPy, modules must be compiled with NumPy 2.0.\n","Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n","\n","If you are a user of the module, the easiest solution will be to\n","downgrade to 'numpy<2' or try to upgrade the affected module.\n","We expect that some modules will need time to support NumPy 2.\n","\n","Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n","  File \"<frozen runpy>\", line 88, in _run_code\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n","    app.launch_new_instance()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1077, in launch_instance\n","    app.start()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n","    self.io_loop.start()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n","    self.asyncio_loop.run_forever()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 608, in run_forever\n","    self._run_once()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 1936, in _run_once\n","    handle._run()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\events.py\", line 84, in _run\n","    self._context.run(self._callback, *self._args)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n","    await self.process_one()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n","    await dispatch(*args)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n","    await result\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n","    await super().execute_request(stream, ident, parent)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n","    reply_content = await reply_content\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n","    res = shell.run_cell(\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n","    return super().run_cell(*args, **kwargs)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n","    result = self._run_cell(\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n","    result = runner(coro)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n","    if await self.run_code(code, result, async_=asy):\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_29968\\1473449029.py\", line 2, in <module>\n","    import pandas as pd\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n","    from pandas.core.api import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\api.py\", line 9, in <module>\n","    from pandas.core.dtypes.dtypes import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\dtypes\\dtypes.py\", line 24, in <module>\n","    from pandas._libs import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n","    import pyarrow.lib as _lib\n"]},{"ename":"AttributeError","evalue":"_ARRAY_API not found","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)","\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"]},{"name":"stderr","output_type":"stream","text":["\n","A module that was compiled using NumPy 1.x cannot be run in\n","NumPy 2.1.2 as it may crash. To support both 1.x and 2.x\n","versions of NumPy, modules must be compiled with NumPy 2.0.\n","Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n","\n","If you are a user of the module, the easiest solution will be to\n","downgrade to 'numpy<2' or try to upgrade the affected module.\n","We expect that some modules will need time to support NumPy 2.\n","\n","Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n","  File \"<frozen runpy>\", line 88, in _run_code\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n","    app.launch_new_instance()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1077, in launch_instance\n","    app.start()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n","    self.io_loop.start()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n","    self.asyncio_loop.run_forever()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 608, in run_forever\n","    self._run_once()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 1936, in _run_once\n","    handle._run()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\events.py\", line 84, in _run\n","    self._context.run(self._callback, *self._args)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n","    await self.process_one()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n","    await dispatch(*args)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n","    await result\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n","    await super().execute_request(stream, ident, parent)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n","    reply_content = await reply_content\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n","    res = shell.run_cell(\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n","    return super().run_cell(*args, **kwargs)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n","    result = self._run_cell(\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n","    result = runner(coro)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n","    if await self.run_code(code, result, async_=asy):\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_29968\\1473449029.py\", line 2, in <module>\n","    import pandas as pd\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n","    from pandas.core.api import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n","    from pandas.core.arrays import Categorical\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n","    from pandas.core.arrays.arrow import ArrowExtensionArray\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n","    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 50, in <module>\n","    from pandas.core import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\ops\\__init__.py\", line 8, in <module>\n","    from pandas.core.ops.array_ops import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\ops\\array_ops.py\", line 56, in <module>\n","    from pandas.core.computation import expressions\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\computation\\expressions.py\", line 21, in <module>\n","    from pandas.core.computation.check import NUMEXPR_INSTALLED\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\computation\\check.py\", line 5, in <module>\n","    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n","    module = importlib.import_module(name)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\importlib\\__init__.py\", line 126, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numexpr\\__init__.py\", line 24, in <module>\n","    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__\n"]},{"ename":"AttributeError","evalue":"_ARRAY_API not found","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)","\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"]},{"name":"stderr","output_type":"stream","text":["\n","A module that was compiled using NumPy 1.x cannot be run in\n","NumPy 2.1.2 as it may crash. To support both 1.x and 2.x\n","versions of NumPy, modules must be compiled with NumPy 2.0.\n","Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n","\n","If you are a user of the module, the easiest solution will be to\n","downgrade to 'numpy<2' or try to upgrade the affected module.\n","We expect that some modules will need time to support NumPy 2.\n","\n","Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n","  File \"<frozen runpy>\", line 88, in _run_code\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n","    app.launch_new_instance()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1077, in launch_instance\n","    app.start()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n","    self.io_loop.start()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n","    self.asyncio_loop.run_forever()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 608, in run_forever\n","    self._run_once()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 1936, in _run_once\n","    handle._run()\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\events.py\", line 84, in _run\n","    self._context.run(self._callback, *self._args)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n","    await self.process_one()\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n","    await dispatch(*args)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n","    await result\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n","    await super().execute_request(stream, ident, parent)\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n","    reply_content = await reply_content\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n","    res = shell.run_cell(\n","  File \"C:\\Users\\User\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n","    return super().run_cell(*args, **kwargs)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n","    result = self._run_cell(\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n","    result = runner(coro)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n","    if await self.run_code(code, result, async_=asy):\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_29968\\1473449029.py\", line 2, in <module>\n","    import pandas as pd\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n","    from pandas.core.api import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\api.py\", line 28, in <module>\n","    from pandas.core.arrays import Categorical\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\arrays\\__init__.py\", line 1, in <module>\n","    from pandas.core.arrays.arrow import ArrowExtensionArray\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\__init__.py\", line 5, in <module>\n","    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\arrays\\arrow\\array.py\", line 64, in <module>\n","    from pandas.core.arrays.masked import BaseMaskedArray\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\arrays\\masked.py\", line 60, in <module>\n","    from pandas.core import (\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\nanops.py\", line 52, in <module>\n","    bn = import_optional_dependency(\"bottleneck\", errors=\"warn\")\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\compat\\_optional.py\", line 135, in import_optional_dependency\n","    module = importlib.import_module(name)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\importlib\\__init__.py\", line 126, in import_module\n","    return _bootstrap._gcd_import(name[level:], package, level)\n","  File \"c:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\bottleneck\\__init__.py\", line 7, in <module>\n","    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,\n"]},{"ename":"AttributeError","evalue":"_ARRAY_API not found","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)","\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"]}],"source":["import threading\n","import pandas as pd\n","import sys\n","from MasterTradePy.api import MasterTradeAPI\n","from MasterTradePy.model import *\n","from MasterTradePy.constant import PriceType, OrderType, TradingSession, Side, TradingUnit, RCode"]},{"cell_type":"code","execution_count":4,"id":"ad02eb72","metadata":{"executionInfo":{"elapsed":5,"status":"aborted","timestamp":1727265705608,"user":{"displayName":"陳昇華","userId":"07161907235039823723"},"user_tz":-480},"id":"ad02eb72"},"outputs":[],"source":["username = 'your username'\n","## 填寫密碼\n","password = 'your password'\n","stock_id_list = [\n","    1476, 1477, 2467, 3006, 3014, 3034, \n","    3042, 3413, 3533, 3557, 5234, 5269, \n","    6202, 8016, 8046, 8081, 9906\n","]"]},{"cell_type":"code","execution_count":5,"id":"733b63c2","metadata":{"executionInfo":{"elapsed":5,"status":"aborted","timestamp":1727265705608,"user":{"displayName":"陳昇華","userId":"07161907235039823723"},"user_tz":-480},"id":"733b63c2"},"outputs":[],"source":["event = threading.Event()"]},{"cell_type":"code","execution_count":6,"id":"ff344703","metadata":{"executionInfo":{"elapsed":5,"status":"aborted","timestamp":1727265705608,"user":{"displayName":"陳昇華","userId":"07161907235039823723"},"user_tz":-480},"id":"ff344703"},"outputs":[],"source":["class ConcreteMarketTrader(MarketTrader):\n","    def OnNewOrderReply(self, data) -> None:\n","        print(data)\n","\n","    def OnChangeReply(self, data) -> None:\n","        print(data)\n","\n","    def OnCancelReply(self, data) -> None:\n","        print(data)\n","\n","    def OnReport(self, data) -> None:\n","        if type(data) is ReportOrder:\n","            if data.order.tableName == \"ORD:TwsOrd\":\n","                print(f'回報資料: 委託書號={data.order.ordNo}, 股票代號={data.order.symbol}, 委託股數={data.orgOrder.qty}, 成交股數={data.order.cumQty}, 訊息={data.lastMessage}, 狀態={data.order.status}')\n","            elif data.order.tableName == \"RPT:TwsDeal\":\n","                print(f'回報資料: 委託書號={data.order.ordNo}, 股票代號={data.order.symbol}, 成交價格={data.order.dealPri}, 成交股數={data.order.cumQty}, 剩餘股數={data.order.leavesQty} 訊息={data.lastMessage}, 狀態={data.order.status}')\n","            elif data.order.tableName == \"RPT:TwsNew\":\n","                print(f'回報資料: 委託書號={data.order.ordNo}, 股票代號={data.order.symbol}, 委託價格={data.orgOrder.price}, 委託股數={data.orgOrder.qty}, 訊息={data.lastMessage}, 狀態={data.order.status}')\n","            else:\n","                print(f'回報資料: 委託書號={data.order.ordNo}, 股票代號={data.order.symbol}, 委託價格={data.orgOrder.price}, 委託股數={data.orgOrder.qty}, 成交股數={data.order.cumQty}, 訊息={data.lastMessage}, 狀態={data.order.status}')\n","\n","    def OnReqResult(self, workID: str, data) -> None:\n","        pass\n","\n","    def OnSystemEvent(self, data: SystemEvent) -> None:\n","        print(f'OnSystemEvent{data}')\n","\n","    def OnAnnouncementEvent(self, data)->None:\n","        print(f'OnAnnouncementEvent:{data}')\n","\n","    def OnError(self, data):\n","        print(data)\n","\n","def OnDigitalSSOEvent(aIsOK, aMsg):\n","    print(f'OnDigitalSSOEvent: {aIsOK} {aMsg}')\n","\n","def OnTAConnStuEvent(aIsOK):\n","    print(f'OnTAConnStuEvent: {aIsOK}')\n","    if aIsOK:\n","        event.set()\n"]},{"cell_type":"code","execution_count":7,"id":"a3913ab6","metadata":{"id":"a3913ab6"},"outputs":[],"source":["def execute_order(api, stock_id_list):\n","    account = 'your account'\n","    price = ''  # 空白表示市價下單\n","    qty = '1000'  # 1張請輸入1000\n","    orderType = OrderType.ROD\n","\n","    if not price:\n","        priceType = PriceType.MKT\n","    else:\n","        priceType = PriceType.LMT\n","\n","    for stock_id in stock_id_list:\n","        symbol = stock_id\n","        order = Order(tradingSession=TradingSession.NORMAL,\n","                      side=Side.Buy,\n","                      symbol=symbol,\n","                      priceType=priceType,\n","                      price=price,\n","                      tradingUnit=TradingUnit.COMMON,\n","                      qty=qty,\n","                      orderType=orderType,\n","                      tradingAccount=account,\n","                      userDef='')\n","        rcode = api.NewOrder(order)\n","        if rcode == RCode.OK:\n","            print(f'已送出委託: {symbol}')\n","        else:\n","            print(f'下單失敗! 股票代號: {symbol}，請再次執行程式，依據回報資料修正輸入')"]},{"cell_type":"code","execution_count":10,"id":"f2f09fa4","metadata":{"id":"f2f09fa4","outputId":"0e642739-08a8-4c04-c9cc-af616057a4e0"},"outputs":[],"source":["def main():\n","    trader = ConcreteMarketTrader()\n","    api = MasterTradeAPI(trader)\n","    api.SetConnectionHost('solace140.masterlink.com.tw:55555')\n","\n","    # 登入交易主機\n","    rc = api.Login(username, password, True, True, True)\n","    if rc == RCode.OK:\n","        print('交易主機連線成功，進行雙因子認證')\n","\n","        # 取得帳戶並進行驗證\n","        accounts = [x[4:] for x in api.accounts]\n","        rcc = api.CheckAccs(tradingAccounts=accounts)\n","        if rcc == RCode.OK:\n","            print('驗證已通過，可執行 API 交易功能')\n","\n","    execute_order(api, stock_id_list)\n","\n","    input(\"Press Enter to finish...\\n\")\n","\n","main()\n"]}],"metadata":{"colab":{"provenance":[]},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.8"}},"nbformat":4,"nbformat_minor":5}
